version: "3.8"

services:
    mongodb-test:
        image: mongo:7.0
        container_name: mongodb-test
        ports:
            - "27018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: testuser
            MONGO_INITDB_ROOT_PASSWORD: testpass
            MONGO_INITDB_DATABASE: problemservice_test
        volumes:
            - mongodb_test_data:/data/db
        command: mongod --quiet --logpath /dev/null

volumes:
    mongodb_test_data:
