import { z } from "zod";

const DifficultyZodEnum = z.enum(["easy", "medium", "hard"]).describe("Difficulty of the problem");
const ProblemExampleZodSchema = z
	.object({
		input: z.string(),
		output: z.string(),
		explanation: z.string().optional().describe("Explanation of the example"),
	})
	.describe("Example of the problem");
export const ProblemCreationZodSchema = z.object({
	title: z.string().min(1),
	slug: z.string().min(1).optional(),
	statement: z.string().min(1),
	difficulty: DifficultyZodEnum,
	examples: z.array(ProblemExampleZodSchema),
	testcaseUrl: z.string().min(1).url().optional(),
	constraints: z.array(z.string()).default([]),
	timeLimitMs: z.number().int().min(1).default(1000), // 1 second minimum
	memoryLimitKB: z.number().int().min(1).default(65536), // 64 MB minimum
	author: z.string().optional(),
	isPublished: z.boolean().default(false).optional(),
	isPremium: z.boolean().default(false),
	submissionsCount: z.number().int().default(0),
	likes: z.number().int().default(0),
	editorial: z.string().optional(),
	companyTags: z.array(z.string()).default([]),
	topicTags: z.array(z.string()).default([]),
});

export const PromptForProblemGenerationSchema = z.object({
	prompt: z.string().min(10).max(1000).describe("Prompt for auto generation"),
});

export const AutoGeneratedProblemSchema = z
	.object({
		title: z.string().describe("Title of the problem"),
		slug: z.string().describe("Slug of the problem"),
		statement: z
			.string()
			.describe("Problem statement in markdown, includes input format at the end"),
		difficulty: DifficultyZodEnum,
		examples: z
			.array(ProblemExampleZodSchema)
			.min(1)
			.max(3)
			.describe("examples (min 1, max 3), input structure needs to be same as the statement"),
		constraints: z.array(z.string()).describe("Constraints of the problem"),
		timeLimitMs: z.number().describe("Time limit in milliseconds"),
		memoryLimitKB: z.number().describe("Memory limit in KB"),
		topicTags: z.array(z.string()).describe("Topic tags of the problem"),
	})
	.describe("Schema for AI generated coding problem");

// all fields optional for update
export const ProblemUpdateZodSchema = ProblemCreationZodSchema.partial();
