import { generateObject } from "ai";
import { aiModels } from "./ai-model/ai-models.ai";
import { AutoGeneratedProblemSchema } from "../validators/problem.validator";
import { z } from "zod";
import logger from "../config/logger.config";
import { serverConfig } from "../config";

export const ProblemGenerationResponseSchema = z
	.object({
		invalidPromptReason: z.string().optional().describe("the reason why the prompt is invalid"),
		problem: AutoGeneratedProblemSchema.optional().describe(
			"Generated coding problem if the prompt is valid"
		),
	})
	.describe(
		"Response from AI for problem generation request where either invalidPromptReason  or problem is present"
	);

export type ProblemGenerationResponseDto = z.infer<typeof ProblemGenerationResponseSchema>;

export async function generateProblemByAI(
	problemGenerationPrompt: string
): Promise<ProblemGenerationResponseDto> {
	logger.info("calling AI to generate problem");
	try {
		const { object: generatedProblemResponse, finishReason } = await generateObject({
			maxOutputTokens: serverConfig.AI.MAX_TOKENS,
			maxRetries: 2,
			model: aiModels.googleFlash,
			prompt: problemGenerationPrompt,
			schema: ProblemGenerationResponseSchema,
			schemaName: "Problem Generation Response",
			system:
				`You are a smart and high rated coding problem generator.\n` +
				`You do not entertain anything other than a prompt which is asking you to generate a coding problem.\n` +
				`If the prompt is not related to a coding problem, you should return a resonse with a indication that the prompt is invalid.\n` +
				`Otherwise, you can generate the coding problem should be challenging and interesting and solvable by human.\n` +
				`Make sure, you do not need any advance data structure to solve the problem unless it is asked`,
		});

		if (finishReason === "length") {
			logger.warn(
				`AI response was truncated due to token limit of ${serverConfig.AI.MAX_TOKENS}. Returning error response.`
			);
			return {
				invalidPromptReason:
					`The prompt generated a response that exceeded the maximum token limit of ${serverConfig.AI.MAX_TOKENS}. Please try with a simpler or more specific prompt.`,
			};
		}

		logger.info("AI Response recieved");
		return generatedProblemResponse;
	} catch (error) {
		// Check if it's a NoObjectGeneratedError due to token limit
		if (
			error instanceof Error &&
			error.message.includes("No object generated") &&
			(error as any).finishReason === "length"
		) {
			logger.warn(
				`AI failed to generate valid object due to token limit of ${serverConfig.AI.MAX_TOKENS}. Returning error response.`
			);
			return {
				invalidPromptReason:
					`The prompt generated a response that exceeded the maximum token limit of ${serverConfig.AI.MAX_TOKENS}. Please try with a simpler or more specific prompt.`,
			};
		}

		// Re-throw other errors
		logger.error("Error generating problem by AI:", error);
		throw error;
	}
}
