import { generateObject } from "ai";
import { aiModels } from "./ai-model/ai-models.ai";
import { AutoGeneratedProblemSchema } from "../validators/problem.validator";
import { z } from "zod";
import logger from "../config/logger.config";

export const ProblemGenerationResponseSchema = z
	.object({
		invalidPromptReason: z.string().optional().describe("the reason why the prompt is invalid"),
		problem: AutoGeneratedProblemSchema.optional().describe(
			"Generated coding problem if the prompt is valid"
		),
	})
	.describe(
		"Response from AI for problem generation request where either invalidPromptReason  or problem is present"
	);

export type ProblemGenerationResponseDto = z.infer<typeof ProblemGenerationResponseSchema>;

export async function generateProblemByAI(
	problemGenerationPrompt: string
): Promise<ProblemGenerationResponseDto> {
	logger.info("calling AI to generate problem");
	const { object: generatedProblemResponse } = await generateObject({
		maxOutputTokens: 1000, // max token 1000 for now for everyone
		maxRetries: 2,
		model: aiModels.googleFlash,
		prompt: problemGenerationPrompt,
		schema: ProblemGenerationResponseSchema,
		schemaName: "Problem Generation Response",
		system:
			`You are a smart and high rated coding problem generator.\n` +
			`You do not entertain anything other than a prompt which is asking you to generate a coding problem.\n` +
			`If the prompt is not related to a coding problem, you should return a resonse with a indication that the prompt is invalid.\n` +
			`Otherwise, you can generate the coding problem should be challenging and interesting and solvable by human.\n` +
			`Make sure, you do not need any advance data structure to solve the problem unless it is asked`,
	});
	logger.info("AI Response recieved");
	return generatedProblemResponse;
}
