version: "3.9"
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: my-rabbitmq # helps to point to the same host always
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
volumes:
    rabbitmq_data:
